### ISSUE TITLE
NoMethodError: undefined method `blank?' for #<Arel::Nodes::Ascending:0x30e1498>

### ISSUE THREAD

**Issue by scriptfans** [rails/arel#456]
On my Nvidia jetson tx1 development board (arm64 architecture, ubuntu 16.04), when I upgrade ruby to 2.3.2, the ActiveRecord's order method is break:

![3dd9b843-74ff-4ce5-99ee-71453ce273b6](https://cloud.githubusercontent.com/assets/359790/20455299/a245647a-ae93-11e6-8944-71fb72af189f.png)

In fact, after I test, This bug is present in several development boards(Nvidia Jetson TK1 and Jetson TX1, Their environment are both rails 5.0.01, ruby 2.3.2, postgresql 9.5):

2.3.0 :001 > User < ActiveRecord::Base
 => true
2.3.0 :002 > User.order(:created_at)
(Object doesn't support #inspect)
 =>
2.3.0 :003 > User.order(:created_at).count
NoMethodError: undefined method `blank?' for #<Arel::Nodes::Ascending:0x30e1408>

For now, in order to solve this problem, I can only downgrade the ruby version to 2.3.1 (2.4.0-preview3 has the same problem), anybody can help me? thanks.

**Comment by rafaelfranca** [comment]
If changing the version of ruby make it works so it is a ruby bug. Thank you for the report.
